baseURL = 'https://mylhassane.github.io/blog/'
canonifyURLs = true
relativeURLs = true
languageCode = 'ar-ma'
title = 'المدونة'
theme = "PaperMod"

[params]
  defaultTheme = "light"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true

[params.assets]
css = ["css/custom.css"]
publishDir = "docs"
