base_url = 'https://mylhassane.github.io/blog/'
language_code = 'ar-ma'
title = 'المدونة'
theme = 'PaperMod'

canonify_urls = true
relative_urls = true

[params]
default_theme = 'light'
show_reading_time = true
show_share_buttons = true
show_post_nav_links = true
show_breadcrumb_crumbs = true

[params.assets]
css = ['css/custom.css']
publish_dir = 'docs'

